server:
  port: 8082
spring:
  profiles:
    active: dev
  application:
    name: push
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: test
      username: test
      password: 123456
      local-datacenter: datacenter1
gg-ws:
  service-url: receive http://127.0.0.1:8083
