server:
  port: 8084
spring:
  profiles:
    active: dev
  application:
    name: send
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
gg-ws:
  service-url: receive http://127.0.0.1:8083
